{% set name = "bcrypt" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a3fd2204178b6d2adcf09cb4f6426ffef54762577a7c9b54c159008cb288c18

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - python
    - pip
    - setuptools >=42.0.0
    - wheel
    - setuptools-rust >=1.7.0
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - bcrypt
    - bcrypt._bcrypt
  requires:
    - pytest >=3.2.1,!=3.3.0
    - pip
  commands:
    - pytest tests
    - pip check

about:
  home: https://github.com/pyca/bcrypt/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Modern password hashing for your software and your servers
  description: |
    Modern password hashing for your software and your servers
  doc_url: https://github.com/pyca/bcrypt/
  dev_url: https://github.com/pyca/bcrypt/

extra:
  recipe-maintainers:
    - djsutherland
    - jan-janssen
